version: 1.0.{build}
image: Visual Studio 2017
skip_tags: true
environment:
  BuildVersion: $(appveyor_build_version)
platform:
  - x64
  - x86
configuration:
  - Debug
  - Release
artifacts:
  - path: '**\*.zip'
    name: zip
deploy:
  provider: GitHub
  auth_token:
    secure: rkO/ImnYrOuUv7sjK6f5VpWduvAAqojRWMWKkLo75iQj2E8A8UuF35DTDP7+Xwiz
  release: v$(appveyor_build_version)
  artifact: zip
  draft: true
build:
  project: build.xml
  verbosity: normal
